create table if not exists public.mood (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mood_type text not null check (mood_type in ('sad', 'stressed', 'neutral', 'happy', 'motivated')),
  check_in_type text not null default 'beforeListening'
    check (check_in_type in ('beforeListening', 'afterListening')),
  playlist_name text,
  helpfulness text check (helpfulness is null or helpfulness in ('yes', 'aLittle', 'no')),
  created_at timestamptz not null default now()
);

alter table public.mood
  add column if not exists check_in_type text not null default 'beforeListening',
  add column if not exists playlist_name text,
  add column if not exists helpfulness text;

create table if not exists public.playlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mood_id uuid references public.mood(id) on delete set null,
  playlist_name text not null,
  source_mood text not null,
  summary text,
  created_at timestamptz not null default now()
);

create table if not exists public.track (
  id bigint generated by default as identity primary key,
  playlist_id bigint not null references public.playlist(id) on delete cascade,
  track_id text,
  title text not null,
  artist text not null,
  stage text not null,
  valence double precision,
  energy double precision,
  preview_url text,
  image_url text,
  external_url text,
  duration_ms integer
);

alter table public.track
  add column if not exists duration_ms integer;

create table if not exists public.favorite (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  playlist_id bigint not null references public.playlist(id) on delete cascade,
  status text not null default 'liked',
  created_at timestamptz not null default now(),
  unique (user_id, playlist_id)
);

alter table public.mood enable row level security;
alter table public.playlist enable row level security;
alter table public.track enable row level security;
alter table public.favorite enable row level security;

create policy "Users can read own mood entries"
on public.mood for select
using (auth.uid() = user_id);

create policy "Users can insert own mood entries"
on public.mood for insert
with check (auth.uid() = user_id);

create policy "Users can read own playlists"
on public.playlist for select
using (auth.uid() = user_id);

create policy "Users can insert own playlists"
on public.playlist for insert
with check (auth.uid() = user_id);

create policy "Users can read tracks from own playlists"
on public.track for select
using (
  exists (
    select 1 from public.playlist
    where playlist.id = track.playlist_id
    and playlist.user_id = auth.uid()
  )
);

create policy "Users can insert tracks for own playlists"
on public.track for insert
with check (
  exists (
    select 1 from public.playlist
    where playlist.id = track.playlist_id
    and playlist.user_id = auth.uid()
  )
);

create policy "Users can manage own favorites"
on public.favorite for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
